global:
  #163服务器
  smtp_smarthost: 'smtp.163.com:25'
  #发邮件的邮箱　　
  smtp_from: 'deariloveyoutoever@163.com'
  #发邮件的邮箱用户名，也就是你的邮箱　　　　　　　　
  smtp_auth_username: 'deariloveyoutoever@163.com'
  #发邮件的邮箱密码
  smtp_auth_password: '01227328'
  #不进行tls验证　　　　　　　　
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: email-monitoring

receivers:
  - name: 'email-monitoring'
    email_configs:
      - to: '735579768@qq.com'