groups:
  - name: node_down
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        user: test
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

  - name: out_of_disk_space
    rules:
    - alert: HostOutOfDiskSpace
      expr: (node_filesystem_avail_bytes{mountpoint="/etc/hostname"}  * 100) / node_filesystem_size_bytes{mountpoint="/etc/hostname"} < 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Host out of disk space (instance {{ $labels.instance }})"
        description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"